name: Deploying Grafana

on: [push]

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2
    - name: Verify Terraform version
      run: terraform --version

    - name: Generate Key Pair
      env:
        EC2_KEY_PEM_64: ${{ secrets.EC2_KEY_PEM_64 }}
        EC2_KEY_PUB_64: ${{ secrets.EC2_KEY_PUB_64 }}
      run: |
        mkdir -p ~/.ssh
        echo $EC2_KEY_PEM_64 | openssl base64 -A -d > ~/.ssh/grafana_key_pair.pem 
        chmod 400 ~/.ssh/grafana_key_pair.pem
        echo $EC2_KEY_PUB_64 | openssl base64 -A -d > ~/.ssh/grafana_key_pair.pub
        chmod 644 ~/.ssh/grafana_key_pair.pub
    - name: Terraform init
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_influxdb_admin_password: ${{ secrets.INFLUXDB_ADMIN_PASSWORD }}
        TF_VAR_influxdb_user_password: ${{ secrets.INFLUXDB_USER_PASSWORD }}
      run: terraform init -input=false

    - name: Terraform Plan
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_influxdb_admin_password: ${{ secrets.INFLUXDB_ADMIN_PASSWORD }}
        TF_VAR_influxdb_user_password: ${{ secrets.INFLUXDB_USER_PASSWORD }}
      run: terraform plan
      
    - name: Terraform validation
      run: terraform validate

    - name: Terraform Deploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        TF_VAR_influxdb_admin_password: ${{ secrets.INFLUXDB_ADMIN_PASSWORD }}
        TF_VAR_influxdb_user_password: ${{ secrets.INFLUXDB_USER_PASSWORD }}
      run: terraform apply -auto-approve -input=false